### ISSUE TITLE
Header colors should not be green

### ISSUE THREAD

**Issue by yosefbernal** [krios2146/obsidian-github#20]
Looking at the source of the Github Dark theme it is evident that the color used for the headings is `#c9d1d9` coming from the `--color-fg-default`, not `#7ee787`. I personally prefer this. Here are the lines in theme.css applying the green color:

![image](https://user-images.githubusercontent.com/33848387/209174323-0b7e3fd7-b944-40d2-b216-019640c8546d.png)

I've changed mine manually but it'd be nice if this was the default. Thanks for sharing this theme :)

**Comment by krios2146** [comment]
Sorry for long answer.

I specially made this header colors green for more readability I guess. I just like how it looks.

And there is style settings plugin where everyone can make their own header colors. So I think I won't be changing the default header colors, sorry if that's disappointing, but I personally don't think it's necessary.

Anyway thanks for submitting this isuue, I will pin it as an answer for "Why are the headers green?" questions.

**Comment by litemotiv** [comment]
Lovely theme but i agree with other commenters that for a 'Github' theme the green color is kind of weird. 

It would feel more logical to use #E6EDF3 like on Github itself, and then use the style settings plugins to make them green if that's what you prefer.

**Comment by ironhak** [comment]
Make default color not green.
