### ISSUE TITLE
I can't add theme with brat

### ISSUE THREAD

**Issue by imed-ghomari** [krios2146/obsidian-github#9]
I'm using [BRAT plugin](https://github.com/TfTHacker/obsidian42-brat) command `Grab a theme for testing from a github repository` and I get this message

![image](https://user-images.githubusercontent.com/38974541/199504778-549cbdd6-9e56-4051-9e83-ad5d0b3f3b12.png)

**Comment by imed-ghomari** [comment]
Didn't notice that it was present in the theme community store (the toggle for `light theme only` was enabled, so It didn't appear when searching even though your latest version adds a light theme).

**Comment by krios2146** [comment]
The community store don't know yet that theme now has a light mode, but it will know soon
